### ISSUE TITLE
Error in the radius of turf.buffer

### ISSUE THREAD

**Issue by Fededgs** [Turfjs/turf#1484]
Working with turf.buffer I notice that the buffering figure of a Polygon was not correct.
In particular, the radius (expressed in meter) wasn't respected during the dilatation.

I report below a test done for buffer a point.
(I know that there is turf.circle but i want to demonstrate the error for the radius).
Code:
```
   var point={
                    "type": "Feature",
                    "properties": {},
                    "geometry": {
                        "type": "Point",
                        "coordinates": [
                        7.237860560417174,
                        45.12233909279541
                        ]
                    }
                   };
   var p = turf.buffer(point, 50, {units:'meters'});
   console.log(turf.area(p));
```
Console:
```
  3885.60
```
Check resultant area:
3885.60=![image](https://user-images.githubusercontent.com/32876183/45543315-909f0f00-b814-11e8-9863-2a7ea1f632c1.png)* R² --> R=35.17m

So,the radius doesn't match the radius of the function.
(It was acceptable if the area was higher for the terrestrial curvature)

With other test, i find out that using radius=71.1 with 'meters', the area after buffer is 7857.98mq and R=50.01m with the formula used before.

Using turf@5.1.6

thanks

**Comment by rowanwins** [comment]
Hi @Fededgs 

Yeah there are some known issues with `@turf/buffer` at the moment, perhaps for the timebeing try rolling back to v4.7.3, and it'll be addressed in v7.

PS Thanks for the handy test case, I'll try and add something like that into the test suite as it should hopefully help avoid mistakes like the one that's currently causing grief.

**Comment by morganherlocker** [comment]
This is likely caused by geodesic and non-geodesic calculations being mixed, but would need to do more digging to confirm.

**Comment by jonnedeprez** [comment]
I just calculated a 13km buffer around a point, and measured 17.6km for the diameter of the resulting circle, which is obviously too small. Interestingly, when I take two opposite points on that same circle, and then for both swap their longitude and latitude, the distance between those two new points is... 26km :-)

Seems like this is a pretty simple bug to me!

**Comment by JamesLMilner** [comment]
@chrispahm thanks for confirming! I will close. Folks can follow up with a new issue if they are still seeing any problems.
