### ISSUE TITLE
MarchingSquares Dependency requires CSP unsafe-eval

### ISSUE THREAD

**Issue by ChrisHSandN** [Turfjs/turf#2233]
Turf Version: 6.5.0

When including turf with a restrictive Content Security Policy which forbids 'unsafe-eval' I get the following error:

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:

I have seen https://github.com/Turfjs/turf/issues/261 and https://github.com/Turfjs/turf/issues/1903 but both have been marked as closed and mention the fix as `concaveman` being updated. 

The eval appears to originate from the code `return new Function("sum","prod","scale","sub",p)(Ut,zt,Xt,Yt)` which is within the `MarchingSquares.js` dependency used by `@turf/isolines`.

I cant find any reports about CSP issues on MarchingSquares; but there have been quite a few updates to https://github.com/RaumZeit/MarchingSquares.js/blob/master/Changelog.md since the `1.2.0` which is used by turf.

**Comment by JamesLMilner** [comment]
This is strange. Looks like MarchingSquares.js is vendored into `marchingsquares-isobands.js`:

https://github.com/Turfjs/turf/blob/84110709afda447a686ccdf55724af6ca755c1f8/packages/turf-isobands/lib/marchingsquares-isobands.js

There's no reference to using `new Function` though so I am confused how that's possible? Are you using a CDN version so I can find the related code in there?

**Comment by JamesLMilner** [comment]
Looking into this a bit more, I'm fairly confident it's from the robust-orientation package: 

https://github.com/Turfjs/turf/blob/cd719cde909db79340d390de39d2c6afe3173062/yarn.lock#L2462

The offending line you describe (`var proc = new Function("sum", "prod", "scale", "sub", code)`) looks like it was fixed in this commit:

https://github.com/mikolalysenko/robust-orientation/commit/cc4c5cf69bcb3587da25cd8640bcb0f4f5c692d1#diff-be3f5063b49f76f4699ab9ffedbecb3dd9837d463c23f9c3d04ff54ac31f95e9

Unfortunately we can't upgrade concaveman right now because it relies on `rbush` which is an ES6 module. We're looking into how to resolve that currently.

**Comment by JamesLMilner** [comment]
For visibility this is caused by the following issue #2200 (not being able to update concaveman)

**Comment by JamesLMilner** [comment]
The fix for this is to bump concaveman to `1.2.1` which would also fix some Webpack bundling issues. However that's not possible at the moment as 1.1.1 uses a ES6 version of `rbush`.

**Comment by ChrisHSandN** [comment]
Apologies for the mis-identification of this as a `MarchingSquares` problem, I was making the assumption it was this package based on the closest license block in the minified file.

![download](https://user-images.githubusercontent.com/13466620/144815921-429ea66f-b6ed-484d-9f80-9f519f3a5d15.png)

I'll close this off in favour of https://github.com/Turfjs/turf/issues/2191

**Comment by TahirAlauddin** [comment]
Still getting this error when trying create a Chrome Extension with Manifest V3.
![image](https://github.com/aframevr/aframe/assets/68107808/0b394e32-1458-413f-a441-4e9634cf8457)

I read the whole discussion, and still didn't get why was it closed as solved. 

And for the record, I am including it directly from a CDN.
